<a href="https://colab.research.google.com/github/SHAIMA-HAQUE/Classification/blob/main/Classification_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Import Packages***

In [ ]:
import numpy as np
import pandas as pd

# ***Import Dataset***

In [ ]:
dataset = pd.read_csv('drug200.csv')
print(dataset)

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]


# ***Check for unique values and Convert them to numeric***

In [ ]:
# Checking unique values in order to convert them to numeric
print(f'''Drugs: {dataset['Drug'].unique()}, 
Sex: {dataset['Sex'].unique()}
Blood Pressure: {dataset['BP'].unique()}
Cholesterol: {dataset['Cholesterol'].unique()}''')

Drugs: ['DrugY' 'drugC' 'drugX' 'drugA' 'drugB'], 
Sex: ['F' 'M']
Blood Pressure: ['HIGH' 'LOW' 'NORMAL']
Cholesterol: ['HIGH' 'NORMAL']


In [ ]:
dataset =  dataset.replace({'Sex':{'F':0, 'M':1}, 
                     'Cholesterol':{'NORMAL':0, 'HIGH':1},
                    'BP':{'LOW':0,'NORMAL':1, 'HIGH':2},
                    'Drug':{'drugA':0, 'drugB':1,'drugC':2,'drugX':3, 'DrugY':4 }})
dataset

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0     23    0   2            1   25.355     4
1     47    1   0            1   13.093     2
2     47    1   0            1   10.114     2
3     28    0   1            1    7.798     3
4     61    0   0            1   18.043     4
..   ...  ...  ..          ...      ...   ...
195   56    0   0            1   11.567     2
196   16    1   0            1   12.006     2
197   52    1   1            1    9.894     3
198   23    1   1            0   14.020     3
199   40    0   0            0   11.349     3

[200 rows x 6 columns]

In [ ]:
X = dataset.iloc[:,1:5].values
Y = dataset.iloc[:,-1].values


In [ ]:
print(X.shape,Y.shape)

(200, 4) (200,)


# ***Split Dataset***

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train.shape, X_test.shape)

(160, 4) (40, 4)


# ***Logistic Regression***

In [ ]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression(solver='lbfgs', max_iter=1000)
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

[4 3 0 2 3 4 3 3 4 3 4 4 4 3 0 4 4 2 0 4 3 3 4 1 4 4 2 4 4 3 2 4 0 0 3 3 4
 4 3 3] [4 4 0 2 3 4 3 3 4 3 4 4 4 3 1 4 4 2 1 4 3 3 4 0 4 4 2 4 4 3 2 4 0 0 3 3 4
 4 3 3]


In [ ]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[ 3  2  0  0  0]
 [ 1  0  0  0  0]
 [ 0  0  3  1  0]
 [ 0  0  0 11  2]
 [ 0  0  0  0 17]]
Accuracy:
 0.85
Precision:
 [0.75       0.         1.         0.91666667 0.89473684]
Recall:
 [0.6        0.         0.75       0.84615385 1.        ]


# ***KNN Classifier***

In [ ]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[ 3  1  0  1  0]
 [ 1  0  0  0  0]
 [ 0  0  2  2  0]
 [ 0  2  1 10  0]
 [ 0  0  0  0 17]]
Accuracy:
 0.8


# ***Decision Tree***

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[ 4  1  0  0  0]
 [ 1  0  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 17]]
Accuracy:
 0.95


# ***Random Forest***

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[ 4  1  0  0  0]
 [ 1  0  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 17]]
Accuracy:
 0.95
